wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/task1/train.py
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691650718.660591
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 5
